services:
  codeharbor-executor:
    build: .
    container_name: codeharbor-executor
    restart: unless-stopped
    volumes:
      - codeharbor_cache:/home/codeharbor/app/cache
      - codeharbor_executions:/home/codeharbor/app/executions
    environment:
      - PORT=3000
      - NODE_ENV=production
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=100
      - DEFAULT_TIMEOUT=60000 # Default timeout in milliseconds
      - CACHE_SIZE_LIMIT=1GB # Max cache size with human-readable values
      - SECRET_KEY=SecretApiToken # Secret key for authentication

volumes:
  codeharbor_cache:
  codeharbor_executions:
